---
- name: install three packages
  hosts: ugadmin
  become: yes
  tasks:
     - name: install httpd wget
       yum:
         name: httpd
         state: installed
     - name: start the service
       service:
         name: httpd
         state: started
         enabled: true
